### ISSUE TITLE
컨트롤러 테스트 추가

### ISSUE THREAD

**Issue by zzawang** [codesquad-masters2024-team02/issue-tracker#11]
## ✏️ 기능 설명
컨트롤러에 실패할 경우의 테스트도 추가한다.

<br><br>

## ✅ TODO
**라벨 생성 API**
- [x] 400 테스트
- [x] 409 테스트
- [x] location 헤더 설정이 되었는지 확인하는 테스트 추가

<br>

**라벨 수정 API**
- [x] 400 테스트
- [x] 404 테스트

<br>

**라벨 삭제 API**
- [x] 404 테스트

<br><br>

**Comment by parksangchu** [comment]
asafsfadsf

**Comment by parksangchu** [comment]
aasdfsaf
